<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTP0CVPT\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTP0CVPT/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTP0CVPT.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTP0CVPT\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTP0CVPT\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TP0CVPT',
    'container.build_id' => 'a920be2c',
    'container.build_time' => 1527120602,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTP0CVPT');
