<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7qiwsz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7qiwsz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC7qiwsz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC7qiwsz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerC7qiwsz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'C7qiwsz',
    'container.build_id' => '11531ee2',
    'container.build_time' => 1526678748,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7qiwsz');
