<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCur4dmj\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCur4dmj/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCur4dmj.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCur4dmj\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCur4dmj\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Cur4dmj',
    'container.build_id' => 'e9f3646a',
    'container.build_time' => 1526596273,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCur4dmj');
